import localFont from "next/font/local";
import "./globals.css";
const redHat = localFont({
  src: "../../public/fonts/RedHatText-VariableFont_wght.ttf",
  variable: "--font-redhat",
});

export const metadata = {
  title: "Desserts",
  description: "Generated by create next app",
};

import Provider from "./ReduxProvider";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${redHat.variable} antialiased`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
